app_login:
   path: /login
   controller: App\Controller\LoginController::login

app_logout:
   path: /logout
   controller: App\Controller\LoginController::logout

homepage:
   path: /
   controller: App\Controller\HomepageController::index

panel:
   path: /panel
   controller: App\Controller\PanelController::index

panel_profile:
   path: /panel/profile
   controller: App\Controller\ProfileController::index

panel_profile_connect:
   path: /panel/profile/connect
   controller: App\Controller\ProfileController::connect