app_login:
   path: /login
   controller: App\Controller\LoginController::login

app_logout:
   path: /logout
   controller: App\Controller\LoginController::logout

homepage:
   path: /
   controller: App\Controller\HomepageController::index

panel:
   path: /panel
   controller: App\Controller\PanelController::index

panel_profile:
   path: /panel/profile
   controller: App\Controller\ProfileController::index

panel_profile_league:
   path: /panel/profile/league
   controller: App\Controller\ProfileController::connect

panel_profile_league_generate_ikp:
   path: /panel/profile/league/generateIKP
   controller: App\Controller\ProfileController::generateIKP

panel_profile_league_verify_summoner:
   path: /panel/profile/league/verifySummoner
   controller: App\Controller\ProfileController::verifySummoner